// Initial DMTV approved-source examples. URLs are starting points — VERIFY each feed
// is live and that usage complies with the source's terms before relying on it.
export const SEED_SOURCES = [
  { name: "Pitchfork — News", source_type: "rss", url: "https://pitchfork.com/feed/feed-news/rss", platform: "pitchfork",
    category_tags: ["rap_news","music_videos","entertainment"], region_tags: ["global"], priority_score: 8, reliability_score: 9,
    rights_risk_level: "low", default_attribution: "Pitchfork", notes: "Reputable music news/reviews." },
  { name: "Stereogum", source_type: "rss", url: "https://www.stereogum.com/feed/", platform: "stereogum",
    category_tags: ["underground_music","rap_news","entertainment"], region_tags: ["global"], priority_score: 7, reliability_score: 8,
    rights_risk_level: "low", default_attribution: "Stereogum", notes: "Music news incl. hip-hop." },
  { name: "Hypebeast", source_type: "rss", url: "https://hypebeast.com/feed", platform: "hypebeast",
    category_tags: ["streetwear","sneakers","fashion","brand_drops","art_design"], region_tags: ["global"], priority_score: 9, reliability_score: 9,
    rights_risk_level: "medium", default_attribution: "Hypebeast", notes: "Streetwear/culture. Inspiration only — never copy posts." },
  { name: "Highsnobiety", source_type: "rss", url: "https://www.highsnobiety.com/feed/", platform: "highsnobiety",
    category_tags: ["streetwear","fashion","brand_drops","aesthetic_reference"], region_tags: ["global"], priority_score: 8, reliability_score: 9,
    rights_risk_level: "medium", default_attribution: "Highsnobiety", notes: "Elevated culture/fashion." },
  { name: "Complex — Music", source_type: "rss", url: "https://www.complex.com/music/rss", platform: "complex",
    category_tags: ["hip_hop","rap_news","entertainment","sneakers"], region_tags: ["global"], priority_score: 8, reliability_score: 8,
    rights_risk_level: "medium", default_attribution: "Complex", notes: "Rap/sneaker/culture. Verify feed path." },
  { name: "HipHopDX", source_type: "rss", url: "https://hiphopdx.com/feed", platform: "hiphopdx",
    category_tags: ["hip_hop","rap_news","underground_music"], region_tags: ["global"], priority_score: 7, reliability_score: 7,
    rights_risk_level: "medium", default_attribution: "HipHopDX", notes: "Fast hip-hop news." },
  { name: "Resident Advisor — Events (Toronto)", source_type: "website", url: "https://ra.co/events/ca/toronto", platform: "ra",
    category_tags: ["nightlife","events"], region_tags: ["toronto"], priority_score: 7, reliability_score: 7,
    rights_risk_level: "medium", default_attribution: "Resident Advisor", notes: "Toronto nightlife/events. May need manual import if no public feed." },
  { name: "BlogTO — Toronto", source_type: "rss", url: "https://www.blogto.com/rss/", platform: "blogto",
    category_tags: ["toronto","events","local_business","nightlife"], region_tags: ["toronto"], priority_score: 6, reliability_score: 7,
    rights_risk_level: "low", default_attribution: "BlogTO", notes: "Local Toronto coverage." },
  { name: "DMTV — Manual Import", source_type: "manual", url: null, platform: "dmtv",
    category_tags: ["aesthetic_reference","creator_culture"], region_tags: ["toronto"], priority_score: 5, reliability_score: 10,
    rights_risk_level: "low", default_attribution: "DMTV", notes: "Paste IG/TikTok/article links here for commentary drafts (API-restricted platforms)." },
  { name: "DMTV — Internal Uploads", source_type: "internal_upload", url: null, platform: "dmtv",
    category_tags: ["aesthetic_reference"], region_tags: ["toronto"], priority_score: 5, reliability_score: 10,
    rights_risk_level: "low", default_attribution: "DMTV", notes: "DMTV-owned media you have rights to use." },
  { name: "Example — YouTube Culture Channel", source_type: "youtube_channel", url: "UC_CHANNEL_ID_HERE", platform: "youtube",
    category_tags: ["podcast_interviews","hip_hop"], region_tags: ["global"], priority_score: 5, reliability_score: 6,
    rights_risk_level: "medium", default_attribution: "YouTube channel", notes: "Set channelId + YOUTUBE_API_KEY, or use the channel RSS feed instead.", is_active: false },
];
