// Expanded DMTV approved-source set across networks.
// URLs are starting points — VERIFY each feed is live and that usage complies with the
// source's terms before relying on it. Reddit feeds reliably exist; some blog feed paths change.
// YouTube channels work as RSS via: https://www.youtube.com/feeds/videos.xml?channel_id=CHANNEL_ID
export const SEED_SOURCES = [
  // ---- Music / hip-hop news (RSS) ----
  { name: "Pitchfork — News", source_type: "rss", url: "https://pitchfork.com/feed/feed-news/rss", platform: "pitchfork", category_tags: ["rap_news","music_videos","entertainment"], region_tags: ["global"], priority_score: 8, reliability_score: 9, rights_risk_level: "low", default_attribution: "Pitchfork" },
  { name: "Stereogum", source_type: "rss", url: "https://www.stereogum.com/feed/", platform: "stereogum", category_tags: ["underground_music","rap_news","entertainment"], region_tags: ["global"], priority_score: 7, reliability_score: 8, rights_risk_level: "low", default_attribution: "Stereogum" },
  { name: "The FADER", source_type: "rss", url: "https://www.thefader.com/rss", platform: "thefader", category_tags: ["hip_hop","streetwear","music_videos","fashion"], region_tags: ["global"], priority_score: 8, reliability_score: 8, rights_risk_level: "medium", default_attribution: "The FADER", notes: "Verify feed path." },
  { name: "XXL", source_type: "rss", url: "https://www.xxlmag.com/feed/", platform: "xxl", category_tags: ["hip_hop","rap_news"], region_tags: ["global"], priority_score: 7, reliability_score: 7, rights_risk_level: "medium", default_attribution: "XXL" },
  { name: "HipHopDX", source_type: "rss", url: "https://hiphopdx.com/feed", platform: "hiphopdx", category_tags: ["hip_hop","rap_news","underground_music"], region_tags: ["global"], priority_score: 7, reliability_score: 7, rights_risk_level: "medium", default_attribution: "HipHopDX" },
  { name: "2DOPEBOYZ", source_type: "rss", url: "https://2dopeboyz.com/feed/", platform: "2dopeboyz", category_tags: ["hip_hop","underground_music"], region_tags: ["global"], priority_score: 6, reliability_score: 6, rights_risk_level: "medium", default_attribution: "2DOPEBOYZ", notes: "Verify feed." },
  { name: "BrooklynVegan", source_type: "rss", url: "https://www.brooklynvegan.com/feed/", platform: "brooklynvegan", category_tags: ["underground_music","entertainment","events"], region_tags: ["global"], priority_score: 6, reliability_score: 7, rights_risk_level: "low", default_attribution: "BrooklynVegan" },

  // ---- Streetwear / fashion / sneakers ----
  { name: "Hypebeast", source_type: "rss", url: "https://hypebeast.com/feed", platform: "hypebeast", category_tags: ["streetwear","sneakers","fashion","brand_drops","art_design"], region_tags: ["global"], priority_score: 9, reliability_score: 9, rights_risk_level: "medium", default_attribution: "Hypebeast", notes: "Inspiration only — never copy posts." },
  { name: "Highsnobiety", source_type: "rss", url: "https://www.highsnobiety.com/feed/", platform: "highsnobiety", category_tags: ["streetwear","fashion","brand_drops","aesthetic_reference"], region_tags: ["global"], priority_score: 8, reliability_score: 9, rights_risk_level: "medium", default_attribution: "Highsnobiety" },
  { name: "Complex — Music", source_type: "rss", url: "https://www.complex.com/music/rss", platform: "complex", category_tags: ["hip_hop","rap_news","entertainment","sneakers"], region_tags: ["global"], priority_score: 8, reliability_score: 8, rights_risk_level: "medium", default_attribution: "Complex", notes: "Verify feed path." },
  { name: "Sneaker News", source_type: "rss", url: "https://sneakernews.com/feed/", platform: "sneakernews", category_tags: ["sneakers","streetwear","brand_drops"], region_tags: ["global"], priority_score: 6, reliability_score: 8, rights_risk_level: "low", default_attribution: "Sneaker News" },
  { name: "Nice Kicks", source_type: "rss", url: "https://www.nicekicks.com/feed/", platform: "nicekicks", category_tags: ["sneakers","streetwear"], region_tags: ["global"], priority_score: 5, reliability_score: 7, rights_risk_level: "low", default_attribution: "Nice Kicks" },
  { name: "Dazed", source_type: "rss", url: "https://www.dazeddigital.com/rss", platform: "dazed", category_tags: ["fashion","art_design","internet_culture","aesthetic_reference"], region_tags: ["global"], priority_score: 6, reliability_score: 7, rights_risk_level: "medium", default_attribution: "Dazed" },

  // ---- Reddit (reliable RSS, strong culture signal) ----
  { name: "r/hiphopheads", source_type: "rss", url: "https://www.reddit.com/r/hiphopheads/top/.rss?t=day", platform: "reddit", category_tags: ["hip_hop","rap_news","underground_music"], region_tags: ["global"], priority_score: 7, reliability_score: 7, rights_risk_level: "medium", default_attribution: "r/hiphopheads", notes: "Community signal — verify claims before posting." },
  { name: "r/streetwear", source_type: "rss", url: "https://www.reddit.com/r/streetwear/top/.rss?t=day", platform: "reddit", category_tags: ["streetwear","fashion"], region_tags: ["global"], priority_score: 6, reliability_score: 6, rights_risk_level: "medium", default_attribution: "r/streetwear" },
  { name: "r/Sneakers", source_type: "rss", url: "https://www.reddit.com/r/Sneakers/top/.rss?t=day", platform: "reddit", category_tags: ["sneakers","streetwear"], region_tags: ["global"], priority_score: 5, reliability_score: 6, rights_risk_level: "medium", default_attribution: "r/Sneakers" },
  { name: "r/toronto", source_type: "rss", url: "https://www.reddit.com/r/toronto/top/.rss?t=day", platform: "reddit", category_tags: ["toronto","nightlife","events","local_business"], region_tags: ["toronto"], priority_score: 6, reliability_score: 6, rights_risk_level: "medium", default_attribution: "r/toronto" },

  // ---- Toronto / local ----
  { name: "BlogTO", source_type: "rss", url: "https://www.blogto.com/rss/", platform: "blogto", category_tags: ["toronto","events","local_business","nightlife"], region_tags: ["toronto"], priority_score: 7, reliability_score: 7, rights_risk_level: "low", default_attribution: "BlogTO" },
  { name: "NOW Toronto", source_type: "rss", url: "https://nowtoronto.com/feed", platform: "nowtoronto", category_tags: ["toronto","events","nightlife","entertainment"], region_tags: ["toronto"], priority_score: 6, reliability_score: 6, rights_risk_level: "low", default_attribution: "NOW Toronto", notes: "Verify feed." },
  { name: "Exclaim! (Canada music)", source_type: "rss", url: "https://exclaim.ca/rss", platform: "exclaim", category_tags: ["underground_music","rap_news","toronto","events"], region_tags: ["toronto","canada"], priority_score: 6, reliability_score: 7, rights_risk_level: "low", default_attribution: "Exclaim!", notes: "Canadian music — verify feed." },
  { name: "Resident Advisor — Toronto Events", source_type: "website", url: "https://ra.co/events/ca/toronto", platform: "ra", category_tags: ["nightlife","events"], region_tags: ["toronto"], priority_score: 7, reliability_score: 6, rights_risk_level: "medium", default_attribution: "Resident Advisor", notes: "May need manual import (no open feed)." },

  // ---- YouTube (works as RSS once you set the channel_id) ----
  { name: "YouTube — set channel_id (interviews)", source_type: "rss", url: "https://www.youtube.com/feeds/videos.xml?channel_id=REPLACE_CHANNEL_ID", platform: "youtube", category_tags: ["podcast_interviews","hip_hop","music_videos"], region_tags: ["global"], priority_score: 5, reliability_score: 7, rights_risk_level: "medium", default_attribution: "YouTube channel", notes: "Replace REPLACE_CHANNEL_ID with a real channelId (from the channel's About > Share > channel ID).", is_active: false },
  { name: "YouTube Search — Toronto rap (needs API key)", source_type: "youtube_search", url: "toronto rap new music", platform: "youtube", category_tags: ["hip_hop","toronto","music_videos"], region_tags: ["toronto"], priority_score: 5, reliability_score: 6, rights_risk_level: "medium", default_attribution: "YouTube", notes: "Requires YOUTUBE_API_KEY.", is_active: false },

  // ---- Podcasts (RSS) ----
  { name: "Podcast — set RSS feed", source_type: "podcast_rss", url: "https://REPLACE_WITH_PODCAST_FEED.xml", platform: "podcast", category_tags: ["podcast_interviews","hip_hop","creator_culture"], region_tags: ["global"], priority_score: 5, reliability_score: 6, rights_risk_level: "low", default_attribution: "Podcast", notes: "Paste a real podcast RSS (Apple/Spotify/host feed).", is_active: false },

  // ---- Social trackers (manual / reference-only) ----
  { name: "Instagram — manual import (reference-only)", source_type: "social_tracker", url: "https://www.instagram.com/", platform: "instagram", category_tags: ["hip_hop","streetwear","nightlife","aesthetic_reference"], region_tags: ["toronto"], priority_score: 6, reliability_score: 5, rights_risk_level: "high", default_attribution: "Instagram", notes: "IG is login-walled/API-restricted. Paste public post links via Culture Feed → Manual import. Commentary + link/reference only — never repost media without rights." },
  { name: "6ixBuzzTV — tracker (reference-only)", source_type: "social_tracker", url: "https://www.instagram.com/6ixbuzztv/", platform: "instagram", category_tags: ["toronto","hip_hop","nightlife"], region_tags: ["toronto"], priority_score: 5, reliability_score: 5, rights_risk_level: "high", default_attribution: "6ixBuzzTV", notes: "Manual import only; commentary/reference, not reposting." },

  // ---- DMTV owned ----
  { name: "DMTV — Manual Import", source_type: "manual", url: null, platform: "dmtv", category_tags: ["aesthetic_reference","creator_culture"], region_tags: ["toronto"], priority_score: 5, reliability_score: 10, rights_risk_level: "low", default_attribution: "DMTV", notes: "Paste any public link for commentary drafts." },
  { name: "DMTV — Internal Uploads", source_type: "internal_upload", url: null, platform: "dmtv", category_tags: ["aesthetic_reference"], region_tags: ["toronto"], priority_score: 5, reliability_score: 10, rights_risk_level: "low", default_attribution: "DMTV", notes: "DMTV-owned media you have rights to use (add to Media Library)." },
];
